@baseurl = http://localhost:8080

### CRIAR PRODUTO

POST {{baseurl}}/restaurant/produto/criar
Content-Type: application/json

{
  "nome": "Feijoada Completa",
  "descricao": "Tradicional feijoada com carnes nobres (carne seca, lombo, costelinha e linguiça calabresa), acompanhada de arroz branco, couve refogada no alho, farofa artesanal e fatias de laranja.",
  "preco": 38.90,
  "categoria": "PRATO_PRINCIPAL"
}

### BUSCAR PRODUTOS

GET {{baseurl}}/restaurant/produto