@baseurl = http://localhost:8080

### ABRIR MESA

POST {{baseurl}}/atendimento/abertura
Content-Type: application/json

{
  "mesaId" : "1",
  "nome" : "Gabriel"
}

### FAZER PEDIDO

POST {{baseurl}}/restaurant/pedido
Content-Type: application/json

{
  "mesaId" : "1",
  "produtosIds": [1,2,2,2,1],
  "observacao" : "Sem obs"
}

### FINALIZAR PEDIDO

PUT {{baseurl}}/restaurant/cozinha/finalizar
Content-Type: application/json

{
  "numeroDoPedido" : "12",
  "mesaId" : "1"
}








### FINALIZAR MESA

PUT {{baseurl}}/atendimento/mesa/1/finalizar

### BUSCAR MESAS
GET {{baseurl}}/atendimento

### BUSCAR PEDIDOS
GET {{baseurl}}/restaurant/pedido

### BUSCAR HISTORICO DE FECHAMENTO
GET {{baseurl}}/atendimento/historico-fechamento


